version: "3.9"

services:
  spark-master:
    image: apache/spark:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
        --host spark-master
    networks:
      - spark-net

  spark-worker-1:
    image: apache/spark:latest
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
        spark://spark-master:7077
    ports:
      - "8081:8081"
    # ADD THIS SECTION
    volumes:
      - ./data:/app/data
    networks:
      - spark-net

  spark-worker-2:
    image: apache/spark:latest
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
        spark://spark-master:7077
    ports:
      - "8082:8081"
    # ADD THIS SECTION
    volumes:
      - ./data:/app/data
    networks:
      - spark-net

  spark-submit:
    build: .
    container_name: spark-submit
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
    working_dir: /app
    command: >
      /opt/spark/bin/spark-submit
        --master spark://spark-master:7077
        --deploy-mode client
        --executor-memory 512m
        --total-executor-cores 2
        /app/app.py
    volumes:
      - ./data:/app/data
    ports:
      - "4040:4040"
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge
