apiVersion: v1
kind: Pod
metadata:
  name: spark-submit-client
spec:
  serviceAccountName: spark
  containers:
    - name: spark-submit-container
      image: spark:latest       # official Spark image
      imagePullPolicy: IfNotPresent
      env:
        # Force JVM's user home to a writable directory
        - name: SPARK_SUBMIT_OPTS
          value: "-Duser.home=/tmp"
      command: ["/opt/spark/bin/spark-submit"]
      args:
        - "--master"
        - "k8s://https://kubernetes.default.svc"
        - "--deploy-mode"
        - "cluster"
        - "--name"
        - "data-analysis"
        - "--conf"
        - "spark.kubernetes.container.image=pyspark-app:latest"
        - "--conf"
        - "spark.kubernetes.container.image.pullPolicy=IfNotPresent"
        - "--conf"
        - "spark.kubernetes.authenticate.driver.serviceAccountName=spark"
        - "--conf"
        - "spark.executor.instances=2"
        - "--conf"
        - "spark.executor.cores=1"
        - "--conf"
        - "spark.executor.memory=512m"
        - "local:///app/app.py"   # Path inside the container
  restartPolicy: Never
